---
title: "Counterfactual Adjusted Causal Model"
author: "Brain K. Masinde"
output:
  html_document:
    df_print: paged
---


```{r}
# clear the working space
rm(list = ls())

library(here)
library(stats) # need this to calculate Mahalanobis Distance
library(parallel) # parallelize
library(dplyr)
library(FNN)
library(cluster)
library(ggplot2)
library(rpart)
library(caret)
```


# Counterfactual Data Input
```{r}
# we need the renaming function for cleaning
melor_2015 <- read.csv(here("data", "melor15_CF_data.csv"))
```

```{r}
# this is going to load cleaned_list which is the list with the clusters
load(here("data", "clusters.RData"))
```

# Counterfactual predictions

## Importing trained models
```{r}

# base models
base_rds_path <- here("adjusted SCM/base models")
base_rds_files <- list.files(base_rds_path, pattern = "\\.rds$", full.names = TRUE)
base_models <- lapply(base_rds_files, readRDS)

# print names of the loaded objects, making sure they are correct
names(base_models) <- basename(base_rds_files)

# Display the list
print(base_models)
```

```{r}
# trunc models
trunc_rds_path <- here("adjusted SCM/trunc models")
trunc_rds_files <- list.files(trunc_rds_path, pattern = "\\.rds$", full.names = TRUE)
trunc_models <- lapply(trunc_rds_files, readRDS)

# print names of the loaded objects, making sure they are correct
names(trunc_models) <- basename(trunc_rds_files)

# Display the list
print(trunc_models)
```


```{r}
# calling hurdle function
source(here("R", "adj_hurdle_function.R"))

names(base_models)  <- c("base_clas_full_model",
                         "base_rain_model",
                         "base_reg_model",
                         "base_roof_light_wall_light_model",
                         "base_roof_light_wall_salv_model",
                         "base_roof_light_wall_strong_model",
                         "base_roof_salv_wall_light_model",
                         "base_roof_salv_wall_salv_model",
                         "base_roof_salv_wall_strong_model",
                         "base_roof_strong_wall_light_model",
                         "base_roof_strong_wall_salv_model",
                         "base_roof_strong_wall_strong_model",
                          "base_wind_model"
                        )

# makes sure the list has correct names
names(trunc_models)  <- c("trunc_rain_model",
                          "trunc_reg_model",
                          "trunc_roof_light_wall_light_model",
                          "trunc_roof_light_wall_salv_model",
                          "trunc_roof_light_wall_strong_model",
                          "trunc_roof_salv_wall_light_model",
                          "trunc_roof_salv_wall_salv_model",
                          "trunc_roof_salv_wall_strong_model",
                          "trunc_roof_strong_wall_light_model",
                          "trunc_roof_strong_wall_salv_model",
                          "trunc_roof_strong_wall_strong_model",
                          "trunc_wind_model"
                         )

adj_counterfactual_hurdle_preds  <- adj_hurdle_function(df = melor_2015,
                                               scm_models_base = base_models,
                                               scm_models_high = trunc_models,
                                               threshold = 0.35 # threshold in train/test models is 0.35
                                               )
```

```{r}
# append the results to the counterfactual dataset
melor_2015  <- melor_2015 %>%
    mutate(damage_preds = adj_counterfactual_hurdle_preds)
```

# Counteractual testing
```{r}
plots_list  <- list()
means_list  <- list()
median_list  <- list()

for (i in seq_along(cleaned_list)) {
  # Get the current entry
  current_entry <- cleaned_list[[i]]

  # Convert the nested list entry to a data frame format
  plot_data <- bind_rows(lapply(names(current_entry), function(region) {
    data.frame(Mun_Code = unlist(current_entry[[region]]), island_regions = region, stringsAsFactors = FALSE)
  }))

  # Merge with original data to get predicted damage
  merged_data <- melor_2015 %>%
    inner_join(plot_data, by = "Mun_Code")

  # Create boxplot
  p <- ggplot(merged_data, aes(x = island_groups, y = damage_preds, fill = island_groups)) +
    geom_boxplot() +
    labs(title = paste("Predicted Damage Distribution - List Entry", i),
         x = "Island Region",
         y = "Predicted Damage") +
    theme_minimal()

 # Save the plot in the list
  plots_list[[i]] <- p

  # Calculate the mean of damage_preds for each island_groups
  mean_values <- merged_data %>%
    group_by(island_groups) %>%
    summarise(mean_damage = mean(damage_preds, na.rm = TRUE))

  # Save the means in the list
  means_list[[i]] <- mean_values

 # Calculate median of the damage_preds for each island groups
  median_values  <- merged_data %>%
    group_by(island_groups) %>%
    summarise(median_damage = median(damage_preds, na.rm = TRUE))

  # save the medians in the list
   median_list[[i]]  <- median_values

}

# Check the list to confirm plots are stored
print(plots_list)
```

```{r}
print(median_list)
```

# Output the counterfactual predictions
Saving the counterfactual predictions for mapping differences  between this 
adjusted causal model and the associational XGBOOST model in QGIS.
```{r}
CF_output <- melor_2015 %>%
  select(Mun_Code, damage_preds) %>%
  rename(adj_scm_CF_M15 = damage_preds)
  
write.csv2(CF_output, file = here("adjusted SCM/outputs", "scm_CF_M15.csv"))
```

