---
title: "Adjsuted Causal Model Testing"
author: "Brian K. Masinde"
output:
  pdf_document: default
  html_notebook: default
---

```{r, message=FALSE}
# clear workshpace
rm(list = ls())

# Load libraries
library(rpart)
library(dplyr)
library(caret)
library(data.table)
library(mlflow)
library(reticulate)
library(Metrics)
library(here)
```

# Inputs
```{r}
# Final Testing data 
# Reading base_test data
base_test <- read.csv(here("data", "base_test.csv"))

# Redaing trunc_test data
truncated_test <- read.csv(here("data", "truncated_test.csv"))

## because we already implemented the hurdle method
df_test <- bind_rows(
  base_test,
  truncated_test
)

nrow(df_test)
```

```{r}
# Import trained BASE models
#   From folder: adjusted SCM/new base models

base_models_list <- list()

# base models file path
base_file_path <- here("adjusted SCM/new base models")
base_wind_model <- readRDS(file.path(base_file_path, 
                                     "dec_base_wind_model_tuned.rds"))


base_class_full_model <- readRDS(file.path(base_file_path, 
                                     "damage_fit_class_full.rds"))
base_reg_model <- readRDS(file.path(base_file_path, 
                                     "base_reg_model.rds"))

base_models_list <- list("base_wind_model" = base_wind_model, 
                         "base_class_full_model" = base_class_full_model, 
                         "base_reg_model" = base_reg_model)
```

```{r}
# Import trained Truncated models
#   From folder: adjusted SCM/new trunc models

# empty list
trunc_models_list <- list()

trunc_file_path <- here("adjusted SCM/new trunc models")

trunc_wind_model <- readRDS(file.path(trunc_file_path,
                                      "trunc_wind_model_tuned.rds"))


trunc_reg_model <- readRDS(file.path(trunc_file_path,
                                      "trunc_reg_model.rds"))

trunc_models_list <- list("trunc_wind_model" = trunc_wind_model,
                          "trunc_reg_model" = trunc_reg_model)
```

```{r}
names(trunc_models_list)
```

```{r}
# importing the hurdle functions
source(here("R", "adj_hurdle_function.R"))
```


# Hurdle Prediction
```{r}
# setting threshold for classification step
threshold = 0.3

preds <- adj_hurdle_function(df = df_test, scm_models_base = base_models_list,
  scm_models_high = trunc_models_list, threshold = threshold

)
```


```{r}
# Define bin edges
# Define bin edges
bins <- c(0, 0.00009, 1, 10, 50, 100)

# Assign data to bins
bin_labels <- cut(df_test$damage_perc, breaks = bins, include.lowest = TRUE, right = TRUE)

# Create a data frame with actual, predicted, and bin labels
data <- data.frame(
  actual = df_test$damage_perc,
  predicted = preds,
  bin = bin_labels
)

# Calculate RMSE per bin
unique_bins <- levels(data$bin) # Get unique bin labels
rmse_by_bin <- data.frame(bin = unique_bins, rmse = NA, count = NA) # Initialize results data frame

for (i in seq_along(unique_bins)) {
  bin_data <- data[data$bin == unique_bins[i], ] # Filter data for the current bin
  rmse_by_bin$rmse[i] <- sqrt(mean((bin_data$actual - bin_data$predicted)^2, na.rm = TRUE)) # Calculate RMSE
  rmse_by_bin$count[i] <- nrow(bin_data) # Count observations in the bin
}

# Calculate weighted average RMSE
total_count <- sum(rmse_by_bin$count, na.rm = TRUE)
w_avg  <- sum(rmse_by_bin$rmse * rmse_by_bin$count)/total_count

# Display RMSE by bin
print(rmse_by_bin)
```

```{r}
w_avg
```

```{r}
# Log metrics using MLFLOW
# set tracking URI
mlflow_set_tracking_uri("http://127.0.0.1:5000")

# Ensure any active run is ended
suppressWarnings(try(mlflow_end_run(), silent = TRUE))

# set experiment
# Logging metrics for model training and the parameters used
mlflow_set_experiment(experiment_name = "Attempt 2: R - SCM - Hurlde - CV (Test metircs)")

# Ensure that MLflow has only one run. Start MLflow run once.
run_name <- paste("Hurdle Run", Sys.time())  # Unique name using current time

as.data.frame(rmse_by_bin)
RMSE_09 <- rmse_by_bin[1, "rmse"]
RMSE_1 <- rmse_by_bin[2, "rmse"]
RMSE_10 <-  rmse_by_bin[3, "rmse"]
RMSE_50 <- rmse_by_bin[4, "rmse"]
RMSE_100 <- rmse_by_bin[5, "rmse"]

# Log threshold & binned RMSE metrics
mlflow_log_metric("thresh", threshold)
mlflow_log_metric("RMSE_09", RMSE_09)
mlflow_log_metric("RMSE_1", RMSE_1)
mlflow_log_metric("RMSE_10", RMSE_10)
mlflow_log_metric("RMSE_50", RMSE_50)
mlflow_log_metric("RMSE_100", RMSE_100)
mlflow_log_metric("w_avg", w_avg)
# End MLflow run
mlflow_end_run()


# NOTE:
# If you get a try catch error message
# the problem is that you have not started mlflow ui
# go to anaconda, initialize the python environment that R uses
# then run mlflow ui in terminal
# then use the url in browser: http://127.0.0.1:5000
```


# OLD CODE
```{r, echo=FALSE, eval=FALSE}
# Define the list of model names for the base model
# base_model_names <- c("clas_full",
#                       "reg",
#                  "wind",
#                  "rain",
#                  "roof_strong_wall_strong",
#                  "roof_strong_wall_light",
#                  "roof_strong_wall_salv",
#                  "roof_light_wall_strong",
#                  "roof_light_wall_light",
#                  "roof_light_wall_salv",
#                  "roof_salv_wall_strong",
#                  "roof_salv_wall_light",
#                  "roof_salv_wall_salv"
#                 )
# 
# # Create a named list to store the models
# base_models_list <- list()
# 
# # Loop over each model name to construct the file path and read the RDS file
# path_base <- here("adjusted SCM/base models")
# for (model_name in base_model_names) {
#   # Construct the file path for the model
#   file_path <- file.path(path_base, paste0("base_", model_name, "_model.rds"))
# 
#   # Read the model and store it in the list with the model name as the key
#   base_models_list[[paste0("base_", model_name, "_model")]] <- readRDS(file_path)
# }
```

```{r, echo=FALSE, eval=FALSE}
# trunc_model_names <- c("reg",
#                  "wind",
#                  "rain",
#                  "roof_strong_wall_strong",
#                  "roof_strong_wall_light",
#                  "roof_strong_wall_salv",
#                  "roof_light_wall_strong",
#                  "roof_light_wall_light",
#                  "roof_light_wall_salv",
#                  "roof_salv_wall_strong",
#                  "roof_salv_wall_light",
#                  "roof_salv_wall_salv"
#                 )
# 
# # Create a named list to store the models
# trunc_models_list <- list()
# 
# # Loop over each model name to construct the file path and read the RDS file
# path_trunc <- here("adjusted SCM/trunc models")
# for (model_name in trunc_model_names) {
#   # Construct the file path for the model
#   file_path <- file.path(path_trunc, paste0("trunc_", model_name, "_model.rds"))
# 
#   # Read the model and store it in the list with the model name as the key
#   trunc_models_list[[paste0("trunc_", model_name, "_model")]] <- readRDS(file_path)
# }
```

```{r, echo=FALSE, eval=FALSE}
# adj_hurdle_function <- function(df, scm_models_base, scm_models_high, threshold) {
#   
# df = df_test
# scm_models_base = base_models_list
# scm_models_high = trunc_models_list
# threshold = 0.3
#   
#   base_col_models_list <- list(
#     wind_max = scm_models_base[["base_wind_model"]]
#     # rain_total = scm_models_base[["base_rain_model"]],
#     # roof_strong_wall_strong = scm_models_base[["base_roof_strong_wall_strong_model"]],
#     # roof_strong_wall_light = scm_models_base[["base_roof_strong_wall_light_model"]],
#     # roof_strong_wall_salv = scm_models_base[["base_roof_strong_wall_salv_model"]],
#     # roof_light_wall_strong = scm_models_base[["base_roof_light_wall_strong_model"]],
#     # roof_light_wall_light = scm_models_base[["base_roof_light_wall_light_model"]],
#     # roof_light_wall_salv = scm_models_base[["base_roof_light_wall_salv_model"]],
#     # roof_salv_wall_strong = scm_models_base[["base_roof_salv_wall_strong_model"]],
#     # roof_salv_wall_light = scm_models_base[["base_roof_salv_wall_light_model"]],
#     # roof_salv_wall_salv = scm_models_base[["base_roof_salv_wall_salv_model"]]
#   )
#   
#   ## common predictions btw class & base regression
#   df1 <-  df %>%
#     mutate(across(names(base_col_models_list), ~ predict(base_col_models_list[[cur_column()]],
#                                                          newdata = df), .names = "{.col}_pred"))
#   
#   # predict for interaction terms
#   # Define wind and rain interaction variables
#   wind_fractions <- c("blue_ss_frac", "yellow_ss_frac", "orange_ss_frac", "red_ss_frac")
#   rain_fractions <- c("blue_ls_frac", "yellow_ls_frac", "orange_ls_frac", "red_ls_frac")
#   
#   for (col in wind_fractions) {
#     new_col_name <- paste0("wind_", col)
#     df1[[new_col_name]] <- df1[[col]] * df1 [["wind_max_pred"]]
#   }
#   
#   # Multiply rain fractions by rain_total_pred
#   for (col in rain_fractions) {
#     new_col_name <- paste0("rain_", col)
#     df1[[new_col_name]] <- df1[[col]] * df1[["rain_total"]]
#   }
#   
#   # WHY DO WE NEED THE OUTCOME VARIABLE HERE FACTOR COLUMNS
#   # factors cleaning for classification task
#   # df$damage_binary_2 <- factor(df$damage_binary,
#   #                                      levels = c("0", "1"),  # Your current levels
#   #                                      labels = c("Damage_below_10", "Damage_above_10"))  # New valid labels
#   
#   ## Step 1: Predict the class label (whether the damage will exceed the threshold)
#   ## class_model should return predicted classes and not probs.
#   ## class_model expects variables "wind_max_pred" and "rain_total_pred" in dataframe df
#   ## type = "prob" for custom threshold specification
#   
#   prob_pred <- predict(scm_models_base$base_class_full_model, df1, type = "prob")[,2]  # Probability of class 1
#   ## assigning final class based on threshold
#   class_pred <- ifelse(prob_pred > threshold, 1, 0) # low threhold of 0.35 can be changed to 0.65/0.75
#   
#   class_pred  <- factor(class_pred, levels = c("0", "1"),  # Your current levels
#                         labels = c("Damage_below_10", "Damage_above_10"))  # New valid labels
#   
#   ## Step 2: Predict the base damage percentage using the base regression model (for low impact cases)
#   ## base expects variables "wind_max_pred" and "rain_total_pred" in dataframe df
#   ## should return the predicted damage percentages
#   base_pred <- predict(scm_models_base$base_reg_model, df1)
#   
#   ## Step 3: Predict the high-impact damage percentage using the high-impact
#   ### SCM models (for high impact cases)
#   ## wind and rainfall predictions are based on high impact data (damage >= 10)
#   
#   trunc_col_models_list <- list(
#     wind_max = scm_models_high[["trunc_wind_model"]]
#     # rain_total = scm_models_high[["trunc_rain_model"]],
#     # roof_strong_wall_strong = scm_models_high[["trunc_roof_strong_wall_strong_model"]],
#     # roof_strong_wall_light = scm_models_high[["trunc_roof_strong_wall_light_model"]],
#     # roof_strong_wall_salv = scm_models_high[["trunc_roof_strong_wall_salv_model"]],
#     # roof_light_wall_strong = scm_models_high[["trunc_roof_light_wall_strong_model"]],
#     # roof_light_wall_light = scm_models_high[["trunc_roof_light_wall_light_model"]],
#     # roof_light_wall_salv = scm_models_high[["trunc_roof_light_wall_salv_model"]],
#     # roof_salv_wall_strong = scm_models_high[["trunc_roof_salv_wall_strong_model"]],
#     # roof_salv_wall_light = scm_models_high[["trunc_roof_salv_wall_light_model"]],
#     # roof_salv_wall_salv = scm_models_high[["trunc_roof_salv_wall_salv_model"]]
#   )
#   # add the predictions of wind and rainfall to the dataframe df
#   df2 <- df %>%
#     mutate(across(names(trunc_col_models_list), ~ predict(trunc_col_models_list[[cur_column()]],
#                                                           newdata = df), .names = "{.col}_pred"))
#   # compute interaction terms based on the predictions
#   for (col in wind_fractions) {
#     new_col_name <- paste0("wind_", col)
#     df2[[new_col_name]] <- df2[[col]] * df2[["wind_max_pred"]]
#   }
#   
#   # Multiply rain fractions by rain_total_pred
#   for (col in rain_fractions) {
#     new_col_name <- paste0("rain_", col)
#     df2[[new_col_name]] <- df2[[col]] * df2[["rain_total"]]
#   }
#   
#   high_pred <- predict(scm_models_high$trunc_reg_model, df2)
#   
#   # Step 4: Apply the hurdle method logic
#   predicted_damage <- ifelse(class_pred == "Damage_above_10", high_pred, base_pred)
#   
#   # Return the predicted damage
#   return(predicted_damage)
# }
```


